/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,vue,ts}",
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary": "#6a0934",
        "primary-container": "#ae8dff",
        "on-surface": "#dee5ff",
        "on-tertiary-fixed": "#380018",
        "secondary": "#c08cf7",
        "on-secondary-fixed": "#4b147d",
        "on-primary": "#39008c",
        "tertiary": "#ff97b5",
        "primary-fixed-dim": "#a27cff",
        "on-secondary-fixed-variant": "#69379c",
        "on-secondary": "#390068",
        "outline-variant": "#40485d",
        "surface-container": "#0f1930",
        "tertiary-dim": "#f0779d",
        "outline": "#6d758c",
        "surface-container-high": "#141f38",
        "primary-fixed": "#ae8dff",
        "inverse-on-surface": "#4d556b",
        "error-dim": "#d73357",
        "on-primary-fixed": "#000000",
        "surface-container-lowest": "#000000",
        "secondary-container": "#5e2c91",
        "primary-dim": "#8455ef",
        "inverse-primary": "#6e3bd7",
        "secondary-dim": "#bb87f1",
        "on-primary-fixed-variant": "#370086",
        "on-background": "#dee5ff",
        "secondary-fixed": "#e4c6ff",
        "error": "#ff6e84",
        "on-error-container": "#ffb2b9",
        "surface-container-low": "#091328",
        "on-surface-variant": "#a3aac4",
        "background": "#060e20",
        "inverse-surface": "#faf8ff",
        "secondary-fixed-dim": "#dab4ff",
        "on-secondary-container": "#e3c4ff",
        "surface-variant": "#192540",
        "on-primary-container": "#2b006e",
        "surface-bright": "#1f2b49",
        "on-error": "#490013",
        "on-tertiary-fixed-variant": "#701039",
        "tertiary-container": "#fd81a8",
        "surface-container-highest": "#192540",
        "tertiary-fixed": "#ff8eb0",
        "on-tertiary-container": "#59002a",
        "tertiary-fixed-dim": "#f67ca3",
        "surface": "#060e20",
        "primary": {
          DEFAULT: "#ba9eff",
          50:  "#faf5ff",
          100: "#f3eaff",
          200: "#e0ccff",
          300: "#c8afff",
          400: "#ba9eff",
          500: "#ae8dff",
          600: "#a27cff",
          700: "#8455ef",
          800: "#6e3bd7",
          900: "#5422b8",
          950: "#39008c",
        },
        "surface-dim": "#060e20",
        "surface-tint": "#ba9eff"
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}